micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db_nossa_casa_codigo?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 607144
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update


#datasources:
#  default:
#    url: jdbc:h2:mem:devDb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    dialect: H2

#jpa:
#  default:
#    properties:
#      hibernate:
#          hbm2ddl:
#              auto: update


